# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install production dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy source code
COPY . .

# Install TypeScript globally for compilation
RUN npm install -g typescript

# Compile TypeScript to JavaScript
RUN npm run build

# Start the server
CMD ["node", "dist/index.js"]
